#!/bin/bash

# Instalar Pre-Requisitos Python y dpkg
sudo pacman -S python python-pip python-setuptools dpkg

# Instalar Ruby Pre-Requisito de varias aplicaciones

sudo pacman -S ruby

# Actualizar e instalar herramientas de OSINT y explotación
sudo pacman -Syu nmap wireshark-qt metasploit aircrack-ng sqlmap nikto tor proxychains bleachbit hydra armitage set burp metagoofil netcat whatweb yay
yay -S cain

# Instalación de Cobalt Strike
cd ~/Descargas/
wget https://cobaltstrike.com/download?invitation=
chmod +x cs
sudo mv cs /usr/bin/

# Instalación de Empire Project
cd ~/Downloads/
git clone https://github.com/BC-SECURITY/Empire.git
cd Empire
sudo ./setup/install.sh

# Instalación de PowerSploit
cd ~/Downloads/
git clone https://github.com/PowerShellMafia/PowerSploit.git
sudo mv PowerSploit /opt

# Instalación de BeEF
cd ~/Downloads/
git clone https://github.com/beefproject/beef.git
cd beef
sudo ./install

# Instalación de Mimikatz
cd ~/Downloads/
git clone https://github.com/gentilkiwi/mimikatz.git
cd mimikatz
make
cd ..

# Clonar TheHarvester y sus dependencias
cd ~/Downloads/
git clone https://github.com/laramies/theHarvester.git
cd theHarvester
sudo pip install -r requirements/base.txt
sudo python setup.py install

# Clonar Shodan y sus dependencias
cd ~/Downloads/
git clone https://github.com/achillean/shodan-python.git
cd shodan-python
sudo python setup.py install

# Instalación de Shellter
cd ~/Descargas/
wget -q 'https://www.shellterproject.com/Downloads/Shellter/Latest/shellter.zip'
unzip shellter.zip
rm shellter.zip

# Instalar SpiderFoot
cd ~/Downloads/
git clone https://github.com/smicallef/spiderfoot.git
cd spiderfoot
sudo pip install -r requirements.txt

# Instalar Foca
cd ~/Downloads/
wget https://github.com/ElevenPaths/FOCA/releases/download/3.4.5/FOCA-3.4.5.zip
unzip FOCA-3.4.5.zip

# Instalar FOCA Online
echo "Visita https://www.elevenpaths.com/es/labstools/foca-online/index.html para instalar FOCA Online"

# Instalar Reconnoitre
cd ~/Downloads/
git clone https://github.com/codingo/Reconnoitre.git
cd Reconnoitre
sudo pip install -r requirements.txt

# Instalar Sublist3r
cd ~/Downloads/
git clone https://github.com/aboul3la/Sublist3r.git
cd Sublist3r
sudo pip install -r requirements.txt

# Instalar EyeWitness
cd ~/Downloads/
git clone https://github.com/FortyNorthSecurity/EyeWitness.git
cd EyeWitness/Python/setup
sudo ./setup.sh

# Instalar WhatWeb
sudo pacman -S whatweb

# Instalar herramientas explotación
sudo pacman -Syu hydra armitage set burp metagoofil netcat

# Instalar Cain and Abel usando yay
yay -S cain

# Instalador de Herramientas BlackArch.

$ curl -O https://blackarch.org/strap.sh
$ echo 5ea40d49ecd14c2e024deecf90605426db97ea0c strap.sh | sha1sum -c
$ chmod +x strap.sh
$ sudo ./strap.sh
$ sudo pacman -Syu


echo "Todas las herramientas han sido instaladas correctamente"
# Instalar BlackArch
cd ~
