#!/bin/bash


# Instalación de Pre-Requisitos Python, dpkg.. etc
sudo pacman -S python
python -m ensurepip --upgrade
sudo pacman -S dpkg 

# Actualización e instalación de herramientas básicas de OSINT
sudo pacman -Syu
sudo pacman -S nmap wireshark-qt metasploit aircrack-ng sqlmap nikto tor proxychains bleachbit -y

# Instalación de theharester
git clone https://github.com/laramies/theHarvester.git
cd theHarvester
python3 -m pip install -r requirements.txt
sudo python3 ./theHarvester.py

# Maltego

# Descargando el paquete binario de Maltego
wget https://maltego-downloads.s3.us-east-2.amazonaws.com/linux/Maltego.v4.3.1.deb   

# Extrayendo el paquete binario
mkdir -p /tmp/maltego
dpkg -x Maltego.v4.3.1.deb /tmp/maltego

# Editando el archivo de configuración
sed -i 's/name="full_name".*/name="full_name" value="Mi Nombre"/' /tmp/maltego/opt/MaltegoCE/etc/Maltego.conf

# Copiando el directorio Maltego a la ubicación deseada
sudo cp -r /tmp/maltego/opt/MaltegoCE /opt/
sudo chown -R root:root /opt/MaltegoCE

# Añadiendo el enlace simbólico para poder ejecutar Maltego desde la línea de comandos
sudo ln -s /opt/MaltegoCE/bin/maltego /usr/bin/maltego

# Limpiando todo
rm MaltegoCE.v4.2.13.13462.deb
rm -rf /tmp/maltego

# Shodan

sudo pacman -S base-devel
git clone https://aur.archlinux.org/python-shodan.git
cd python-shodan
makepkg -sic

# Instalación de Cobalt Strike
cd ~/Descargas/
wget https://cobaltstrike.com/download?invitation=
chmod +x cs
sudo mv cs /usr/bin/

# Instalación de Metasploit Framework
cd ~/Downloads/
curl https://raw.githubusercontent.com/rapid7/metasploit-omnibus/master/config/templates/metasploit-framework-wrappers/msfupdate.erb > msfinstall
sudo chmod 755 msfinstall
sudo ./msfinstall

# Instalación de Empire Project
cd ~/Downloads/
git clone https://github.com/BC-SECURITY/Empire.git
cd Empire
sudo ./setup/install.sh

# Instalación de PowerSploit
cd ~/Downloads/
git clone https://github.com/PowerShellMafia/PowerSploit.git
sudo mv PowerSploit /opt

# Instalación de BeEF
cd ~/Downloads/
git clone https://github.com/beefproject/beef.git
cd beef
sudo ./install

# Instalación de Mimikatz
cd ~/Downloads/
git clone https://github.com/gentilkiwi/mimikatz.git
cd mimikatz
make
cd ..

# Instalación de Shellter
cd ~/Downloads/
wget -q 'https://www.shellterproject.com/Downloads/Shellter/Latest/shellter.zip'
unzip shellter.zip
rm shellter.zip

# Fin del script
echo "Todas las herramientas han sido instaladas correctamente"
