#!/bin/bash

# Actualización e instalación de herramientas básicas de OSINT
sudo pacman -Syu
sudo pacman -S nmap wireshark-qt theharvester maltego shodan metasploit aircrack-ng sqlmap nikto tor proxychains bleachbit -y

# Instalación de Cobalt Strike
cd ~/Downloads/
wget https://cobaltstrike.com/download?invitation=
chmod +x cs
sudo mv cs /usr/bin/

# Instalación de Metasploit Framework
cd ~/Downloads/
curl https://raw.githubusercontent.com/rapid7/metasploit-omnibus/master/config/templates/metasploit-framework-wrappers/msfupdate.erb > msfinstall
sudo chmod 755 msfinstall
sudo ./msfinstall

# Instalación de Empire Project
cd ~/Downloads/
git clone https://github.com/BC-SECURITY/Empire.git
cd Empire
sudo ./setup/install.sh

# Instalación de PowerSploit
cd ~/Downloads/
git clone https://github.com/PowerShellMafia/PowerSploit.git
sudo mv PowerSploit /opt

# Instalación de BeEF
cd ~/Downloads/
git clone https://github.com/beefproject/beef.git
cd beef
sudo ./install

# Instalación de Mimikatz
cd ~/Downloads/
git clone https://github.com/gentilkiwi/mimikatz.git
cd mimikatz
make
cd ..

# Instalación de Shellter
cd ~/Downloads/
wget -q 'https://www.shellterproject.com/Downloads/Shellter/Latest/shellter.zip'
unzip shellter.zip
rm shellter.zip

# Fin del script
echo "Todas las herramientas han sido instaladas correctamente"
