#!/bin/bash

# Instalar Pre-Requisitos Python y dpkg
sudo pacman -S --noconfirm python python-pip python-setuptools dpkg ruby

# Instalador de Herramientas BlackArch.
curl -O https://blackarch.org/strap.sh
echo 5ea40d49ecd14c2e024deecf90605426db97ea0c strap.sh | sha1sum -c
chmod +x strap.sh
sudo ./strap.sh
sudo pacman -S --noconfirm
sudo pacman -S yay --noconfirm
sudo pacman -S fakeroot --noconfirm
sudo pacman -S wget

echo "Todas las herramientas han sido instaladas correctamente"

# Actualizar e instalar herramientas de OSINT y explotación
sudo pacman -S --noconfirm nmap 
sudo pacman -S --noconfirm wireshark-qt
sudo pacman -S --noconfirm metasploit
sudo pacman -S --noconfirm aircrack-ng
sudo pacman -S --noconfirm sqlmap
sudo pacman -S --noconfirm nikto
sudo pacman -S --noconfirm tor
sudo pacman -S --noconfirm proxychains
sudo pacman -S --noconfirm bleachbit
sudo pacman -S --noconfirm hydra
sudo pacman -S --noconfirm armitage
sudo pacman -S --noconfirm netcat
sudo pacman -S --noconfirm whatweb
sudo pacman -S --noconfirm firefox
sudo pacman -S --noconfirm mimikatz
sudo pacman -S --noconfirm beef
sudo pacman -S --noconfirm powersploit
sudo pacman -S --noconfirm empire
sudo pacman -S --noconfirm theharvester
sudo pacman -Syu --noconfirm shellter
sudo pacman -Syu spiderfoot

# Shodan API
cd ~/Downloads/
git clone https://github.com/ismailtasdelen/shodansploit.git
cd shodansploit
python shodansploit.py 
