#!/bin/bash

# Instalar pre-requisitos y herramientas de OSINT
sudo pacman -S --noconfirm wine wine-mono wine-gecko python python-pip python-setuptools dpkg ruby nmap wireshark-qt metasploit aircrack-ng sqlmap nikto tor proxychains bleachbit hydra armitage netcat whatweb firefox mimikatz beef powersploit empire theharvester

# Instalar Yay
sudo pacman -S --noconfirm yay fakeroot

# Instalar herramientas de OSINT adicionales con Yay
yay -S --noconfirm cain

# Instalación de Cobalt Strike
cd ~/Downloads/
wget https://cobaltstrike.com/download?invitation=
chmod +x cs
sudo mv cs /usr/bin/

# Clonar Shodan y sus dependencias 
cd ~/Downloads/ 
git clone https://github.com/achillean/shodan-python.git 
cd shodan-python 
sudo python setup.py install 

# Instalación de Shellter
cd ~/Downloads/
wget -q 'https://www.shellterproject.com/Downloads/Shellter/Latest/shellter.zip'
unzip shellter.zip
rm shellter.zip 

# Instalar SpiderFoot 
cd ~/Downloads/ 
git clone https://github.com/smicallef/spiderfoot.git 
cd spiderfoot 
sudo pip install -r requirements.txt 
sudo pip install M2Crypto cherrypy mako requests bs4 lxml netaddr pysocks ipwhois phonenumbers pyOpenSSL ssdeep pytz stem PyPDF2 olefile openxmllib tldextract cryptography pyopenssl ndg_httpsclient pyasn1 google-api-python-client oauth2client google-auth google-auth-oauthlib google-auth-httplib2 XlsxWriter xlrd xlwt future python-docx dnslib exifread Flask flask_cors flask_login flask_sqlalchemy itsdangerous Jinja2 MarkupSafe SQLAlchemy Werkzeug click dominate visitor Flask-WTF WTForms email_validator idna certifi urllib3 chardet pycparser cffi pycparser six packaging pyparsing zipp importlib-metadata typing-extensions keyring jeepney SecretStorage dbus-python entrypoints keyrings.alt

echo "Todas las herramientas han sido instaladas correctamente"
