#!/bin/bash

# Clonamos el repositorio de TheHarvester
git clone https://github.com/laramies/theHarvester.git
cd theHarvester

# Instalamos las dependencias de Python de TheHarvester
sudo pacman -S python python-pip python-setuptools
sudo pip install -r requirements/base.txt

# Instalamos TheHarvester
sudo python setup.py install > /tmp/theHarvester.log 2>&1
if [ $? -ne 0 ]; then
  echo "Error: TheHarvester no se pudo instalar correctamente. Por favor revise /tmp/theHarvester.log para más detalles."
fi

# Clonamos el repositorio de Shodan
git clone https://github.com/achillean/shodan-python.git
cd shodan-python

# Instalamos Shodan
sudo python setup.py install > /tmp/shodan.log 2>&1
if [ $? -ne 0 ]; then
  echo "Error: Shodan no se pudo instalar correctamente. Por favor revise /tmp/shodan.log para más detalles."
fi

# Instalamos Maltego
sudo pacman -Syy
wget https://www.paterva.com/malv42/community/MaltegoCE.v4.2.13.13462.deb
sudo pacman -S gdebi
sudo gdebi -n MaltegoCE.v4.2.13.13462.deb
