#!/bin/bash

# Clonamos el repositorio de TheHarvester
cd Descargas
git clone https://github.com/laramies/theHarvester.git
cd theHarvester

# Instalamos las dependencias de Python de TheHarvester
sudo apt-get install python3 python3-pip python3-setuptools
sudo pip3 install -r requirements/base.txt

# Instalamos TheHarvester
sudo python3 setup.py install > /tmp/theHarvester.log 2>&1
if [ $? -ne 0 ]; then
  echo "Error: TheHarvester no se pudo instalar correctamente. Por favor revise /tmp/theHarvester.log para más detalles."
fi
